### ISSUE TITLE
Connection Response from Phantom

### ISSUE THREAD

**Issue by baileyalo** [phantom/docs#41]
No response from Phantom after connect 

    // Handle a `connect` response from Phantom
    if (/onConnect/.test(url.pathname)) {
      const sharedSecretDapp = nacl.box.before(
        bs58.decode(params.get('phantom_encryption_public_key')!),
        dappKeyPair.secretKey,
      );
      const connectData = decryptPayload(
        params.get('data')!,
        params.get('nonce')!,
        sharedSecretDapp,
      );
      setSharedSecret(sharedSecretDapp);
      setSession(connectData.session);
      setPhantomWalletPublicKey(new PublicKey(connectData.public_key));
      console.log(`connected to ${connectData.public_key.toString()}`);
    }

**Comment by lempiy** [comment]
I confirm that. It was broken in latest release of Phantom app. It worked in previous version.

**Comment by Timadigwe** [comment]
Is there any update on this , im having this same  issue

**Comment by skmanish** [comment]
It is fixed by phantom team. 
Please update phantom to 22.10.24 or beyond

**Comment by baileyalo** [comment]
@skmanish I tried in my react-native app still not getting a response from phantom 
am running version 22.10.31(123) android

**Comment by Timadigwe** [comment]
Same here it doesn't even redirect back to my app , after upgrading my phantom app.
Can someone help out please 
Your suggestions would be highly appreciated
